language: python

os:
  - osx
  # - linux

python:
  - 2.7

before_install:
  - brew update
  - brew tap homebrew/science
  - brew install adol-c
  - brew install boost --with-mpi --without-single
  - brew install cppad --with-adol-c --with-boost --with-openmp
  - brew install asl
  - brew install metis
  - pip install numpy scipy
  - pip install algopy
  - pip install git+https://github.com/b45ch1/pycppad.git
  - pip install git+https://github.com/b45ch1/pyadolc.git
  - pip install pytest-cov

install:
  - echo "[ASL]" > site.cfg
  - echo "asl_dir = $(brew --prefix asl)" >> site.cfg
  - python setup.py install

script:
  - py.test -v --cov-report= --cov=nlp tests/

after_success:
  coveralls
