language: objective-c  # force osx for now.

os:
  - osx
#   # - linux

notifications:
    email: never

before_install:
  - brew update
  - brew install python
  - brew tap homebrew/science
  - brew uninstall -f adol-c boost cppad asl metis
  - brew install adol-c
  - brew install boost-python
  - brew install cppad --with-adol-c
  - brew install asl
  - brew install metis
  - pip install -q virtualenv
  - virtualenv ~/.venv
  - source ~/.venv/bin/activate
  - pip install -q numpy scipy
  - pip install -q git+https://github.com/optimizers/pysparse.git
  - pip install -q git+https://github.com/PythonOptimizers/pykrylov.git@develop
  - pip install -q algopy
  - pip install -q git+https://github.com/b45ch1/pycppad.git
  - cd $HOME && git clone https://github.com/b45ch1/pyadolc.git
  - cd pyadolc && { echo '\n' | python setup.py install; } && cd $TRAVIS_BUILD_DIR
  - pip install -q pytest-cov

install:
  - echo "[ASL]" > site.cfg
  - echo "asl_dir = $(brew --prefix asl)" >> site.cfg
  - python setup.py install

script:
  - nlp_lbfgs.py examples/rosenbr.nl
  - nlp_trunk.py examples/rosenbr.nl
  - nlp_dercheck.py examples/rosenbr.nl
  # - py.test -v --cov-report= --cov=nlp tests/  # when repository goes public
  - py.test -v --cov=nlp tests/

# Uncomment when repository goes public
# after_success:
#   coveralls
